version: "3.7"
services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: chisato-emby_server_1
      APP_PORT: 8096
      PROXY_AUTH_ADD: 'false'
  server:
    image: linuxserver/emby:4.8.6@sha256:48503bae813c9262986d4b9909172a4fcd3cb7716c03726abd36d4b94f813dbb
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
      - ${UMBREL_ROOT}/data/storage/Media:/DATA/Media
    ports:
      # Service auto-discovery
      - 7359:7359/udp
